Feature/searchable dropdown
liip-amboss/forge pull request #91
Opened 2020-02-19 13:39 UTC by JonasNiestroj

# Checklist (Only for frontend changes)
- [x] Changes tested in IE11
- [x] Responsive
- [x] Documented "How to use it"
- [x] Documented "How to install"
- [x] Featured in Styleguide

# Summary of this PR
I added a basic select component which uses the vue-multiselect library.
The component is customizable with the vue-multiselect options

2020-02-19 17:04 UTC, rotwurstesser commented
Looks nice so far!

2020-09-28 15:05 UTC, schtibe requested changes
There is quite some noise in this merge request, some formatting changes of the package.json and so on. Maybe we could sort this out by having another MR that fixes those things and then apply this one? I guess we can work more thoroughly here since we don't have a deadline ;)

2020-09-28 15:05 UTC, schtibe commented on frontend/src/components/Select.vue
> +export default {
I'm unsure about this component. Same with input. We try to create those wrapper components to make things easier to use, but out in the field, I find that often those wrapper components don't provide all the flexibility we need. So we start extending those components, and soon we implement all the stuff of the child into the wrapper component. And we almost end up 

And in this one here, we don't actually add anything. It's good to have an example though!

I have an idea for the Input.vue to improve, will write this somewhere else.

2020-10-01 15:34 UTC, schtibe commented on frontend/styleguide.config.js
> +  'regexpu-core',
OK, weird, i checked out `master` and this stuff is already there...

2020-10-01 15:35 UTC, schtibe commented on frontend/styleguide.config.js
> +    path.join(__dirname, 'node_modules/svgxuse'),
This already is in master!!

2020-10-05 14:30 UTC, merged